version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
    - libgl1
  tools:
    python: "3"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
