codecov:
  bot: "Codecov"
comment:
  layout: "reach, diff, files"
  behavior: default
coverage:
  precision: 3
  status:
    project:
      default:
        target: 100%
        threshold: 5%
    patch:
      default:
        target: 100%
        threshold: 0%
github_checks:
  annotations: true
