# Get GitHub Actions job matrix from workflow configuration file
#
# This reusable workflow extracts the JSON matrix stored in the variable
# `WORKFLOW_MATRIX_CONFIG` in `.github/workflows/workflow_config`
# so that the same matrix can be reused in different jobs, reducing
# duplicate code.

name: Get Workflow Matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: Matrix of inputs for which to run GitHub Actions tests
        value: ${{ jobs.build.outputs.matrix }}

jobs:
  build:
    name: Get Workflow Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v4

      - name: Run Setup Action
        uses: ./.github/workflows/composite-actions/load-workflow-config

      - name: Set up Workflow Matrix
        id: set-matrix
        run: echo "matrix=${{ env.WORKFLOW_MATRIX_CONFIG }}" >> $GITHUB_OUTPUT
